
name: test

on:
  push:
    branches:
      - master
    tags-ignore:
      - '*'

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
      - name: Run release-notify-action
        uses: wowvendor/release-notify-action@v1
        with:
          jira_login: m.pak@bpcbt.com
          jira_api_key: ${{ secrets.JIRA_API_KEY }}
          jira_org: wowvendor
          commit_message: ${{ github.event.head_commit.message }}
          slack_token: ${{ secrets.SLACK_TOKEN }}
          slack_channel: C01T49QL4G0
          debug: true
